<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>IDE0130; IDE0305</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Diode.Core/Diode.Core.csproj"/>
  </ItemGroup>

</Project>
